image: ubuntu:latest

before_script:
    - apt-get update -y
    - apt-get install rsync openssh-client -y
    - mkdir -p $HOME/.ssh
    - chmod 700 $HOME/.ssh
    - echo "$SSH_HOST ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDDoLhgavd5zWF8C+/BKlM15LNtpaaUkL03b44KYKxJ0DVf54zd6PO4pZxmZYorkNtsVHkOsJbXm2rmVrvdGBMU=" > $HOME/.ssh/known_hosts
    - chmod 644 $HOME/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null


deploy:
    script:
        - rsync -e "ssh" -avz --delete --exclude="\.*" * $SSH_USER@$SSH_HOST:$SSH_ROOT/
    only:
        - master
